### ISSUE TITLE
Missed token returned by ankr_getAccountBalance method

### ISSUE THREAD

**Issue by aminhdev** [Ankr-network/ankr.js#13] opened 2022-11-09 10:45 UTC
***Get account balance by running this***
```
curl --location --request POST 'https://rpc.ankr.com/multichain' \
--header 'Content-Type: application/json' \
--header 'X-API-KEY: $$$$$$$$$$$$$$$$$$$$$$' \
--data-raw '{
    "jsonrpc": "2.0",
    "method": "ankr_getAccountBalance",
    "params": {  
        "walletAddress": "0xdaf835f11537fca6db91e91c266d153200f46d52",
        "pageSize": 10000
    },
    "id": 1
}'
```

***This is list tokens of [0xdaf835f11537fca6db91e91c266d153200f46d52](https://optimistic.etherscan.io/tokenholdings?a=0xdaf835f11537fca6db91e91c266d153200f46d52)***
![image](https://user-images.githubusercontent.com/22216884/200808417-5aca53cc-bfef-47f3-9c97-b8c0c76ccf37.png)

***Expected result***
ETH token returned in the result 

***Current result***
Missed ETH token in the result

**Comment by bogatyr285** [comment] 2022-11-09 13:06
Greetings!

The issue is that in optimism chain you didn't receive ETH price?

```
{
    "jsonrpc": "2.0",
    "method": "ankr_getAccountBalance",
    "params": {  
        "blockchain":["optimism"],
        "walletAddress": "0xdaf835f11537fca6db91e91c266d153200f46d52",
        "pageSize": 10000
    },
    "id": 1
}
```
like this query results zero prices?

**Comment by aminhdev** [comment] 2022-11-09 14:50
> Greetings!
> 
> The issue is that in optimism chain you didn't receive ETH price?
> 
> ```
> {
>     "jsonrpc": "2.0",
>     "method": "ankr_getAccountBalance",
>     "params": {  
>         "blockchain":["optimism"],
>         "walletAddress": "0xdaf835f11537fca6db91e91c266d153200f46d52",
>         "pageSize": 10000
>     },
>     "id": 1
> }
> ```
> 
> like this query results zero prices?

Sorry to confuse you, I should have described this issues in more detail

I ran this method
```
curl --location --request POST 'https://rpc.ankr.com/multichain' \
--header 'Content-Type: application/json' \
--header 'X-API-KEY: $$$$$$$$$$$$$$$$$$$$$$' \
--data-raw '{
    "jsonrpc": "2.0",
    "method": "ankr_getAccountBalance",
    "params": {
        "blockchain":["optimism"],
        "walletAddress": "0xdaf835f11537fca6db91e91c266d153200f46d52",
        "pageSize": 10000
    },
    "id": 1
}'
```

This is the result returned by  ankr_getAccountBalance method above
```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "totalBalanceUsd": "0",
    "assets": [{
      "blockchain": "optimism",
      "tokenName": "Synthetix Network Token",
      "tokenSymbol": "SNX",
      "tokenDecimals": 18,
      "tokenType": "ERC20",
      "contractAddress": "0x8700daec35af8ff88c16bdf0418774cb3d7599b4",
      "holderAddress": "0xdaf835f11537fca6db91e91c266d153200f46d52",
      "balance": "0.005883172287304306",
      "balanceRawInteger": "5883172287304306",
      "balanceUsd": "0",
      "tokenPrice": "0",
      "thumbnail": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/optimism/assets/0x8700dAec35aF8Ff88c16BdF0418774CB3D7599B4/logo.png"
    }, {
      "blockchain": "optimism",
      "tokenName": "Dai Stablecoin",
      "tokenSymbol": "DAI",
      "tokenDecimals": 18,
      "tokenType": "ERC20",
      "contractAddress": "0xda10009cbd5d07dd0cecc66161fc93d7c9000da1",
      "holderAddress": "0xdaf835f11537fca6db91e91c266d153200f46d52",
      "balance": "0.12201000950112047",
      "balanceRawInteger": "122010009501120470",
      "balanceUsd": "0",
      "tokenPrice": "0",
      "thumbnail": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/arbitrum/assets/0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1/logo.png"
    }, {
      "blockchain": "optimism",
      "tokenName": "Optimism",
      "tokenSymbol": "OP",
      "tokenDecimals": 18,
      "tokenType": "NATIVE",
      "holderAddress": "0xdaf835f11537fca6db91e91c266d153200f46d52",
      "balance": "0.000062982972903158",
      "balanceRawInteger": "62982972903158",
      "balanceUsd": "0",
      "tokenPrice": "0",
      "thumbnail": "https://www.ankr.com/protocol/static/media/optimism.53b7f574.svg"
    }]
  }
}
```

You can see no ETH token info is returned in the result even though ETH token actually exists in the account 
[Link scan](https://optimistic.etherscan.io/tokenholdings?a=0xdaf835f11537fca6db91e91c266d153200f46d52)
![image](https://user-images.githubusercontent.com/22216884/200861494-ecae5048-983c-421d-bda6-1bde2b03e275.png)

**Comment by bogatyr285** [comment] 2022-11-09 14:59
Got it. Yes, we have some issues with optimism network.
Thanks for report. We'll figure it out

**Comment by shlomich** [comment] 2023-04-02 13:56
I think the API is alright, however since Optimism uses Ethereum as it's NATIVE token you can notice the tokenType that shows "NATIVE", I do agree though it needs to be "Ethereum" with that native tokenType aswell. But you can surely add a small validation to get that right. :P

**Comment by aminhdev** [comment] 2023-04-03 02:34
> I think the API is alright, however since Optimism uses Ethereum as it's NATIVE token you can notice the tokenType that shows "NATIVE", I do agree though it needs to be "Ethereum" with that native tokenType aswell. But you can surely add a small validation to get that right. :P

I don't think the API is alright, the contributor confirmed that here is an issue https://github.com/Ankr-network/ankr.js/issues/13#issuecomment-1308891485
But for now I have to do as your suggestion 👍

**Comment by RedCuckoo** [comment] 2023-11-08 14:48
Closing as this has been fixed. ETH is now returned as NATIVE as well as Optimism.

**Closed by RedCuckoo** 2023-11-08 14:48 UTC

**Comment by aminhdev** [comment] 2024-03-29 07:55
This problem come again, for now I ETH is not returned in the result 
I tried to run this code 

```
curl --location --request POST 'https://rpc.ankr.com/multichain/<my-premium-api-key>' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "method": "ankr_getAccountBalance",
    "params": {  
        "walletAddress": "0xE935c4E5DcCB41A811e33AB5f03901E491cd9BE3",
        "blockchain": "optimism"
    },
    "id": 1
}'
`
```

This is response

``` {
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "totalBalanceUsd": "0.029995444084849786",
    "totalCount": 1,
    "assets": [
      {
        "blockchain": "optimism",
        "tokenName": "USD Coin",
        "tokenSymbol": "USDC",
        "tokenDecimals": 6,
        "tokenType": "ERC20",
        "contractAddress": "0x0b2c639c533813f4aa9d7837caf62653d097ff85",
        "holderAddress": "0xe935c4e5dccb41a811e33ab5f03901e491cd9be3",
        "balance": "0.029997",
        "balanceRawInteger": "29997",
        "balanceUsd": "0.029995444084849786",
        "tokenPrice": "0.99994813097475702",
        "thumbnail": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/optimism/assets/0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85/logo.png"
      }
    ],
    "syncStatus": {
      "timestamp": 1711698299,
      "lag": "-2m",
      "status": "synced"
    }
  }
}
```

The problem here is no ETH included in the response, I want to confirm that ETH is already in my account at this request time, you can check it here https://gyazo.com/d98b7d2a98ec87725b22cc6dca1827b3

**Comment by RedCuckoo** [comment] 2024-03-29 11:54
@aminhdev Could you double check please and send an output of the curl also? Because it returns three balances at that account from every our cluster and from rpc endpoint.

**Comment by aminhdev** [comment] 2024-04-01 04:09
> @aminhdev Could you double check please and send an output of the curl also? Because it returns three balances at that account from every our cluster and from rpc endpoint.

Sorry to disturb you here. I've created a support ticket and received a response. I will discuss it in the supported ticket instead.
